-- HEMS schema migration 002
-- Creates: public.hems_adaptive_schedules table for Phase 4
-- Target DB: postgresql://homelab:homelab@192.168.0.80:5432/homelab

BEGIN;

-- -------------------------------------------------------------------------
-- public.hems_adaptive_schedules — adaptive heating schedule slots
-- -------------------------------------------------------------------------
-- Stores 24h adaptive schedules generated by Phase 4 algorithm.
-- Each row is a single 15-min time slot with target temp and mode.

CREATE TABLE IF NOT EXISTS public.hems_adaptive_schedules (
    id              BIGSERIAL PRIMARY KEY,
    room_id         TEXT        NOT NULL,                -- e.g. 'living_room'
    time_slot       TIMESTAMPTZ NOT NULL,                -- Start of 15-min slot
    target_temp     NUMERIC(5,2) NOT NULL,               -- Target temperature (°C)
    mode            TEXT        NOT NULL DEFAULT 'comfort', -- 'comfort', 'eco', 'off'
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for common queries
CREATE INDEX IF NOT EXISTS idx_hems_adaptive_schedules_room_time
    ON public.hems_adaptive_schedules (room_id, time_slot DESC);

CREATE INDEX IF NOT EXISTS idx_hems_adaptive_schedules_date
    ON public.hems_adaptive_schedules (DATE(time_slot));

-- Ensure no duplicate slots for same room
CREATE UNIQUE INDEX IF NOT EXISTS idx_hems_adaptive_schedules_unique_slot
    ON public.hems_adaptive_schedules (room_id, time_slot);

COMMIT;
